[package]
name = "rtoml"
version = "0.0.2"
authors = ["Samuel Colvin <s@muelcolvin.com>"]
edition = "2018"

[dependencies]
toml = "0.5.5"
serde = "1.0.104"
pyo3 = {version = "0.8.5", features = ["extension-module"]}

[lib]
name = "_rtoml"
crate-type = ["cdylib"]
